# Generated by Django 4.0.3 on 2022-04-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_contrato_parqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='contratoid',
            field=models.ForeignKey(db_column='ContratoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.contrato'),
        ),
    ]
