# Generated by Django 4.0.3 on 2022-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_viatura_contratoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registomovimento',
            name='matricula',
            field=models.CharField(blank=True, db_column='Matricula', max_length=255, null=True),
        ),
    ]
