# Generated by Django 4.0.3 on 2022-04-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_registomovimento_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='contratoid',
            field=models.ForeignKey(db_column='ContratoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.contrato'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='reservaid',
            field=models.ForeignKey(db_column='ReservaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.reserva'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='viaturaid',
            field=models.ForeignKey(db_column='ViaturaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.viatura'),
        ),
    ]
