# Generated by Django 4.0.3 on 2022-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_lugar_contratoid_alter_lugar_reservaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaMatriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(db_column='Pais', max_length=255)),
                ('formato', models.CharField(db_column='Formato', max_length=255)),
            ],
        ),
    ]
