# Generated by Django 4.0.4 on 2022-05-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_tabelamatriculas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Periodicidade',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='viaturaid',
            field=models.ForeignKey(blank=True, db_column='ViaturaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.viatura'),
        ),
        migrations.DeleteModel(
            name='TabelaPrecos',
        ),
    ]
