# Generated by Django 4.0.3 on 2022-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_delete_dia_delete_periodicidade_pagamento_viaturaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='foto',
            field=models.CharField(blank=True, db_column='Foto', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
