# Generated by Django 4.0.4 on 2022-06-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_parque_foto_delete_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='zonaid',
            field=models.ForeignKey(blank=True, db_column='ZonaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.zona'),
        ),
    ]
