# Generated by Django 4.0.4 on 2022-06-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_alter_reclamacao_registo_movimentoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='registo_movimentoid',
            field=models.ForeignKey(blank=True, db_column='Registo-movimentoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.registomovimento'),
        ),
    ]
